#
# Makefile for the hisense sensors drivers.
#
obj-$(CONFIG_HS_SNS_APDS993X)	+= apds993x.o
obj-$(CONFIG_HS_SNS_CM36686)	+= cm36686.o
obj-$(CONFIG_HS_SNS_ELAN_ALSPS)	+= epl259x.o
obj-$(CONFIG_HS_SNS_BMA2X2)	+= bma2x2.o
obj-$(CONFIG_HS_SNS_KXTJ9)	+= kxtj9.o
obj-$(CONFIG_HS_SNS_MC3XXX)	+= mc3xxx.o
obj-$(CONFIG_HS_SNS_AKM09911)	+= akm09911.o
obj-$(CONFIG_HS_SNS_AKM09916)	+= akm09916.o
obj-$(CONFIG_HS_SNS_ST480)	+= st480.o
